### PR TITLE
FT-456 : possibly serialize ft fanout to disk, handle upgrade/layout …

### PR DESCRIPTION
**Pull request by georgelorchpercona**
…version change

Serialized fanout in ft-header and exposed ft_header.fanout value in tokuftdump.

### CODE REVIEW

**Comment by georgelorchpercona** [comment]
jenkins http://jenkins.percona.com/view/TokuDB/job/ft-index-param/14/

Trying to run ctest format upgrade tests locally, will post results if successful.

**Comment by georgelorchpercona** [comment]
Forgot to mention, I actually review this w/ Rich P. and got his blessing with the only caveat being that the upgrade tests should be run just to make sure it works on older versioned files.

**Comment by georgelorchpercona** [comment]
OK, finally got the upgrate ctests working correctly and lo-and-behold they found an issue. It's been corrected now and the upgrade tests pass just fine (these other failures are known failures that have yet to be dealt with):

99% tests passed, 14 tests failed out of 3310

Total Test time (real) = 3533.43 sec

The following tests FAILED:
        2204 - ydb/helgrind_helgrind2.tdb (Failed)
        2205 - ydb/helgrind_helgrind3.tdb (Failed)
        2212 - ydb/drd_mid_test_stress_with_verify.tdb (Failed)
        2216 - ydb/drd_mid_test_stress3.tdb (Failed)
        2220 - ydb/drd_mid_test_stress5.tdb (Failed)
        2224 - ydb/drd_mid_test_stress1.tdb (Failed)
        2227 - ydb/drd_tiny_test_stress0.tdb (Failed)
        2229 - ydb/drd_mid_test_stress0.tdb (Failed)
        2233 - ydb/drd_mid_test_stress7.tdb (Failed)
        2235 - ydb/drd_tiny_test_stress_openclose.tdb (Failed)
        2237 - ydb/drd_mid_test_stress_openclose.tdb (Failed)
        2241 - ydb/drd_mid_test_stress4.tdb (Failed)
        2243 - ydb/drd_tiny_test_stress2.tdb (Failed)
        2245 - ydb/drd_mid_test_stress2.tdb (Failed)
Errors while running CTest

**Comment by christianrober** [comment]
These changes look good to me.  Really clean.   George, did you modify or add upgrade tests as part of this work effort?

**Comment by georgelorchpercona** [comment]
I ran the current tests which should test the update from old header 
versions up to the new 28, but I did not add any new tests/databases yet 
as I am unsure of what the correct process is and am awaiting some 
answers on that (i.e. is there a tool used to generate the test data, 
what tests need touched, etc...)



On 07/02/2015 05:25 AM, Christian wrote:
>
> These changes look good to me. Really clean. George, did you modify or 
> add upgrade tests as part of this work effort?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Tokutek/ft-index/pull/283#issuecomment-118013300>.
>

-- 
George O. Lorch III
Software Engineer, Percona
+1-888-401-3401 x542 US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by prohaska7** [comment]
Run generate-upgrade-recovery-logs --clean and --dirty and copy the directories that were created to the tokudb.data currently hosted on subversion.

**Comment by georgelorchpercona** [comment]
Fantastic, thanks Rich, I have an email draft I was going to send you 
last week on this and never got back to it.

On 07/02/2015 07:31 AM, Rik Prohaska wrote:
>
> Run generate-upgrade-recovery-logs --clean and --dirty and copy the 
> directories that were created to the tokudb.data currently hosted on 
> subversion.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Tokutek/ft-index/pull/283#issuecomment-118050991>.
>

-- 
George O. Lorch III
Software Engineer, Percona
+1-888-401-3401 x542 US/Arizona (GMT -7)
skype: george.ormond.lorch.iii

**Comment by prohaska7** [comment]
the new tests need to be added to ft/tests/CMakeLists.txt.  Maybe this cmake file should be changed to automatically find the data so that it does not need to be hacked going forward.

**Comment by prohaska7** [comment]
should probably generate 7.5.7 stress test data directories.  see tokudb.data/old-stress-test-envs/7.5.0/README.

**Comment by georgelorchpercona** [comment]
OK, created new upgrade test data, fixed upgrade test to use globbing to add tests for the test data present and regenerated 7.5.0 stress test data.

All tests passed with the normal ongoing failures that still need to be fixed. Still really need to get a jenkins slave set up that can run just the stress and upgrade tests for us.

Upgrade recovery log tests:

Start testing: Jul 05 12:48 MST
----------------------------------------------------------
248/3314 Testing: ft/test-upgrade-recovery-logs
248/3314 Test: ft/test-upgrade-recovery-logs
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.21 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs" time elapsed: 00:00:00
----------------------------------------------------------

276/3314 Testing: ft/test-upgrade-recovery-logs-26-clean
276/3314 Test: ft/test-upgrade-recovery-logs-26-clean
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-26-clean"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-26-clean" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-26-clean" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-26-clean" time elapsed: 00:00:00
----------------------------------------------------------

277/3314 Testing: ft/test-upgrade-recovery-logs-24-clean
277/3314 Test: ft/test-upgrade-recovery-logs-24-clean
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-24-clean"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-24-clean" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.30 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-24-clean" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-24-clean" time elapsed: 00:00:00
----------------------------------------------------------

282/3314 Testing: ft/test-upgrade-recovery-logs-27-dirty
282/3314 Test: ft/test-upgrade-recovery-logs-27-dirty
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-27-dirty"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-27-dirty" start time: Jul 05 12:48 MST
Output:
---------------------------------------------------------<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-27-dirty" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-27-dirty" time elapsed: 00:00:00
----------------------------------------------------------

281/3314 Testing: ft/test-upgrade-recovery-logs-28-dirty
281/3314 Test: ft/test-upgrade-recovery-logs-28-dirty
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-28-dirty"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-28-dirty" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-28-dirty" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-28-dirty" time elapsed: 00:00:00
----------------------------------------------------------

279/3314 Testing: ft/test-upgrade-recovery-logs-25-clean
279/3314 Test: ft/test-upgrade-recovery-logs-25-clean
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-25-clean"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-25-clean" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   2.66 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-25-clean" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-25-clean" time elapsed: 00:00:02
----------------------------------------------------------

275/3314 Testing: ft/test-upgrade-recovery-logs-27-clean
275/3314 Test: ft/test-upgrade-recovery-logs-27-clean
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-27-clean"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-27-clean" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   2.76 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-27-clean" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-27-clean" time elapsed: 00:00:02
----------------------------------------------------------

283/3314 Testing: ft/test-upgrade-recovery-logs-24-dirty

283/3314 Test: ft/test-upgrade-recovery-logs-24-dirty
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-24-dirty"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-24-dirty" start time: Jul 05 12:49 MST
Output:
----------------------------------------------------------
Cannot upgrade TokuFT version 24 database.  Previous improper shutdown detected.
<end of output>
Test time =   0.13 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-24-dirty" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-24-dirty" time elapsed: 00:00:00
----------------------------------------------------------

280/3314 Testing: ft/test-upgrade-recovery-logs-25-dirty
280/3314 Test: ft/test-upgrade-recovery-logs-25-dirty
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-25-dirty"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-25-dirty" start time: Jul 05 12:48 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   2.86 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-25-dirty" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-25-dirty" time elapsed: 00:00:02
----------------------------------------------------------

284/3314 Testing: ft/test-upgrade-recovery-logs-26-dirty
284/3314 Test: ft/test-upgrade-recovery-logs-26-dirty
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-26-dirty"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-26-dirty" start time: Jul 05 12:49 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.23 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-26-dirty" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-26-dirty" time elapsed: 00:00:00
----------------------------------------------------------

278/3314 Testing: ft/test-upgrade-recovery-logs-28-clean
278/3314 Test: ft/test-upgrade-recovery-logs-28-clean
Command: "/ssd/toku/vadim/ft-index-build/ft/tests/test-upgrade-recovery-logs" "/ssd/toku/vadim/ft-index/../tokudb.data/upgrade-recovery-logs-28-clean"
Directory: /ssd/toku/vadim/ft-index-build/ft/tests
"ft/test-upgrade-recovery-logs-28-clean" start time: Jul 05 12:49 MST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.22 sec
----------------------------------------------------------
Test Passed.
"ft/test-upgrade-recovery-logs-28-clean" end time: Jul 05 12:49 MST
"ft/test-upgrade-recovery-logs-28-clean" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by christianrober** [comment]
This new CMake change looks good to me.

Do we know if the db_version number needs to updated as part of these changes?   I assume it does not need to be updated.

I  poked around upgrade_test_simple.cc, to see if this test needs to have versioned data added to it.  My current guess is that this test is only really useful when changing the structure of leaf and internal nodes.

So, I am assuming this would not apply to header changes, as is the case here (for fanout), and that upgrade_test_simple.cc does not need to be updated.

**Comment by georgelorchpercona** [comment]
db_version seems to refer to the ydb api version and not anything particularly internal to ft-index. It is defined currently as 4.6.19 and doesn't appear to have changed within ft-index since 2012. So, no, I don;t think we need to worry about it :)

**Comment by prohaska7** [comment]
I agree.

**Pull request merged**
